
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author laboratorio
 */
public class JFrame_Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_Principal.class.getName());

    /**
     * Creates new form JFrame_Principal
     */
    public JFrame_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_ghost1 = new javax.swing.JButton();
        jButton_ghost2 = new javax.swing.JButton();
        jButton_frutinha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_ghost1.setText("1");
        jButton_ghost1.setFocusable(false);

        jButton_ghost2.setText("2");
        jButton_ghost2.setFocusable(false);

        jButton_frutinha.setText("@");
        jButton_frutinha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_frutinhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton_ghost1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton_frutinha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(jButton_ghost2)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton_ghost1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_ghost2)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_frutinha)
                        .addGap(65, 65, 65))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_frutinhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_frutinhaKeyPressed
        // TODO add your handling code here:
        
        System.out.println("Pressionei..." + evt.getKeyCode());
        
        
        switch (evt.getKeyCode()) {
            case 38:
                new Thread() {
                    @Override
                    public void run() {
                        Movimenta.cima(jButton_ghost1);            
                    }
                }.start();
                
                break;
            case 40:
                new Thread() {
                   @Override
                   public void run() {
                       Movimenta.baixo(jButton_ghost1, JFrame_Principal.this);
                   }
               }.start();
                
                break;
            case 37:
                new Thread() {
                    @Override
                    public void run() {
                        Movimenta.esquerda(jButton_ghost1);
                    }
                }.start();
                
                break;
            case 39:
                new Thread() {
                    @Override
                    public void run() {
                        Movimenta.direita(jButton_ghost1, JFrame_Principal.this);
                    }
                }.start();
                
                break;
            case 87:
                System.out.println("Indo para cima");
                Movimenta.cima(jButton_ghost2);
                break;
            case 83:
                System.out.println("Indo para baixo");
                Movimenta.baixo(jButton_ghost2, this);
                break;
            case 65:
                System.out.println("INdo para esquerda");
                Movimenta.esquerda(jButton_ghost2);
                break;
            case 68:
                System.out.println("Indo para direita");
                Movimenta.direita(jButton_ghost2, this);
                break;
            default:
                throw new AssertionError();
        }
        
        if (jButton_ghost1.getBounds().intersects(jButton_frutinha.getBounds())) {
            System.out.println("PEguei");
            Movimenta.sorteiaPosicao(jButton_frutinha, this);
        }
        
          if (jButton_ghost2.getBounds().intersects(jButton_frutinha.getBounds())) {
            System.out.println("PEguei");
            Movimenta.sorteiaPosicao(jButton_frutinha, this);
        }
        
    }//GEN-LAST:event_jButton_frutinhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_frutinha;
    private javax.swing.JButton jButton_ghost1;
    private javax.swing.JButton jButton_ghost2;
    // End of variables declaration//GEN-END:variables
}
